[server]
maxUploadSize = 10
maxMessageSize = 10
enableCORS = true
enableXsrfProtection = true
port = 8501
headless = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501
