[server]
maxUploadSize = 10
maxMessageSize = 10
enableCORS = true
enableXsrfProtection = true
port = 8501
headless = true

[client]
showErrorDetails = true

[logger]
level = "info"

[browser]
gatherUsageStats = false
